{"name": "Пользователь не может авторизоваться, если указаны не корректные учетные данные", "status": "passed", "start": 1711871291495, "stop": 1711871291784, "uuid": "60dc79d7-a143-4012-ad34-099081c6f5bd", "historyId": "7e530524902b2808ab56296e27502094", "testCaseId": "7e530524902b2808ab56296e27502094", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_negative", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "PC"}, {"name": "thread", "value": "2288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}