{"name": "Пользователь не может авторизоваться, если указаны не корректные учетные данные", "status": "passed", "start": 1711561106535, "stop": 1711561106963, "uuid": "d6519c8d-6518-4d2d-93ae-4895c8df4c79", "historyId": "7e530524902b2808ab56296e27502094", "testCaseId": "7e530524902b2808ab56296e27502094", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_negative", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "PC"}, {"name": "thread", "value": "14972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}